// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/viniciuscluna/tc-fiap-customer/internal/customer/infrastructure/api/dto"
)

// MockCustomerController is an autogenerated mock type for the CustomerController type
type MockCustomerController struct {
	mock.Mock
}

type MockCustomerController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerController) EXPECT() *MockCustomerController_Expecter {
	return &MockCustomerController_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: customer
func (_m *MockCustomerController) Add(customer *dto.AddCustomerRequestDto) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.AddCustomerRequestDto) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerController_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockCustomerController_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - customer *dto.AddCustomerRequestDto
func (_e *MockCustomerController_Expecter) Add(customer interface{}) *MockCustomerController_Add_Call {
	return &MockCustomerController_Add_Call{Call: _e.mock.On("Add", customer)}
}

func (_c *MockCustomerController_Add_Call) Run(run func(customer *dto.AddCustomerRequestDto)) *MockCustomerController_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.AddCustomerRequestDto))
	})
	return _c
}

func (_c *MockCustomerController_Add_Call) Return(_a0 error) *MockCustomerController_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerController_Add_Call) RunAndReturn(run func(*dto.AddCustomerRequestDto) error) *MockCustomerController_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCpf provides a mock function with given fields: cpf
func (_m *MockCustomerController) GetByCpf(cpf uint) (*dto.GetCustomerResponseDto, error) {
	ret := _m.Called(cpf)

	if len(ret) == 0 {
		panic("no return value specified for GetByCpf")
	}

	var r0 *dto.GetCustomerResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dto.GetCustomerResponseDto, error)); ok {
		return rf(cpf)
	}
	if rf, ok := ret.Get(0).(func(uint) *dto.GetCustomerResponseDto); ok {
		r0 = rf(cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetCustomerResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(cpf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomerController_GetByCpf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCpf'
type MockCustomerController_GetByCpf_Call struct {
	*mock.Call
}

// GetByCpf is a helper method to define mock.On call
//   - cpf uint
func (_e *MockCustomerController_Expecter) GetByCpf(cpf interface{}) *MockCustomerController_GetByCpf_Call {
	return &MockCustomerController_GetByCpf_Call{Call: _e.mock.On("GetByCpf", cpf)}
}

func (_c *MockCustomerController_GetByCpf_Call) Run(run func(cpf uint)) *MockCustomerController_GetByCpf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCustomerController_GetByCpf_Call) Return(_a0 *dto.GetCustomerResponseDto, _a1 error) *MockCustomerController_GetByCpf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomerController_GetByCpf_Call) RunAndReturn(run func(uint) (*dto.GetCustomerResponseDto, error)) *MockCustomerController_GetByCpf_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerController creates a new instance of MockCustomerController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerController {
	mock := &MockCustomerController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
