// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/viniciuscluna/tc-fiap-customer/internal/customer/domain/entities"
)

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: customer
func (_m *MockCustomerRepository) Add(customer *entities.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockCustomerRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - customer *entities.Customer
func (_e *MockCustomerRepository_Expecter) Add(customer interface{}) *MockCustomerRepository_Add_Call {
	return &MockCustomerRepository_Add_Call{Call: _e.mock.On("Add", customer)}
}

func (_c *MockCustomerRepository_Add_Call) Run(run func(customer *entities.Customer)) *MockCustomerRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Customer))
	})
	return _c
}

func (_c *MockCustomerRepository_Add_Call) Return(_a0 error) *MockCustomerRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Add_Call) RunAndReturn(run func(*entities.Customer) error) *MockCustomerRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCpf provides a mock function with given fields: cpf
func (_m *MockCustomerRepository) GetByCpf(cpf string) (*entities.Customer, error) {
	ret := _m.Called(cpf)

	if len(ret) == 0 {
		panic("no return value specified for GetByCpf")
	}

	var r0 *entities.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Customer, error)); ok {
		return rf(cpf)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Customer); ok {
		r0 = rf(cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cpf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomerRepository_GetByCpf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCpf'
type MockCustomerRepository_GetByCpf_Call struct {
	*mock.Call
}

// GetByCpf is a helper method to define mock.On call
//   - cpf string
func (_e *MockCustomerRepository_Expecter) GetByCpf(cpf interface{}) *MockCustomerRepository_GetByCpf_Call {
	return &MockCustomerRepository_GetByCpf_Call{Call: _e.mock.On("GetByCpf", cpf)}
}

func (_c *MockCustomerRepository_GetByCpf_Call) Run(run func(cpf string)) *MockCustomerRepository_GetByCpf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCustomerRepository_GetByCpf_Call) Return(_a0 *entities.Customer, _a1 error) *MockCustomerRepository_GetByCpf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomerRepository_GetByCpf_Call) RunAndReturn(run func(string) (*entities.Customer, error)) *MockCustomerRepository_GetByCpf_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
