// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	commands "github.com/viniciuscluna/tc-fiap-customer/internal/customer/usecase/commands"
)

// MockAddCustomerUseCase is an autogenerated mock type for the AddCustomerUseCase type
type MockAddCustomerUseCase struct {
	mock.Mock
}

type MockAddCustomerUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddCustomerUseCase) EXPECT() *MockAddCustomerUseCase_Expecter {
	return &MockAddCustomerUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockAddCustomerUseCase) Execute(command *commands.AddCustomerCommand) error {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*commands.AddCustomerCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAddCustomerUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAddCustomerUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.AddCustomerCommand
func (_e *MockAddCustomerUseCase_Expecter) Execute(command interface{}) *MockAddCustomerUseCase_Execute_Call {
	return &MockAddCustomerUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockAddCustomerUseCase_Execute_Call) Run(run func(command *commands.AddCustomerCommand)) *MockAddCustomerUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.AddCustomerCommand))
	})
	return _c
}

func (_c *MockAddCustomerUseCase_Execute_Call) Return(_a0 error) *MockAddCustomerUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAddCustomerUseCase_Execute_Call) RunAndReturn(run func(*commands.AddCustomerCommand) error) *MockAddCustomerUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAddCustomerUseCase creates a new instance of MockAddCustomerUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddCustomerUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddCustomerUseCase {
	mock := &MockAddCustomerUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
