// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/viniciuscluna/tc-fiap-customer/internal/customer/domain/entities"
	dto "github.com/viniciuscluna/tc-fiap-customer/internal/customer/infrastructure/api/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockCustomerPresenter is an autogenerated mock type for the CustomerPresenter type
type MockCustomerPresenter struct {
	mock.Mock
}

type MockCustomerPresenter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerPresenter) EXPECT() *MockCustomerPresenter_Expecter {
	return &MockCustomerPresenter_Expecter{mock: &_m.Mock}
}

// Present provides a mock function with given fields: customer
func (_m *MockCustomerPresenter) Present(customer *entities.Customer) *dto.GetCustomerResponseDto {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Present")
	}

	var r0 *dto.GetCustomerResponseDto
	if rf, ok := ret.Get(0).(func(*entities.Customer) *dto.GetCustomerResponseDto); ok {
		r0 = rf(customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetCustomerResponseDto)
		}
	}

	return r0
}

// MockCustomerPresenter_Present_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Present'
type MockCustomerPresenter_Present_Call struct {
	*mock.Call
}

// Present is a helper method to define mock.On call
//   - customer *entities.Customer
func (_e *MockCustomerPresenter_Expecter) Present(customer interface{}) *MockCustomerPresenter_Present_Call {
	return &MockCustomerPresenter_Present_Call{Call: _e.mock.On("Present", customer)}
}

func (_c *MockCustomerPresenter_Present_Call) Run(run func(customer *entities.Customer)) *MockCustomerPresenter_Present_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Customer))
	})
	return _c
}

func (_c *MockCustomerPresenter_Present_Call) Return(_a0 *dto.GetCustomerResponseDto) *MockCustomerPresenter_Present_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerPresenter_Present_Call) RunAndReturn(run func(*entities.Customer) *dto.GetCustomerResponseDto) *MockCustomerPresenter_Present_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerPresenter creates a new instance of MockCustomerPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerPresenter {
	mock := &MockCustomerPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
