// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/viniciuscluna/tc-fiap-customer/internal/customer/domain/entities"
	commands "github.com/viniciuscluna/tc-fiap-customer/internal/customer/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockGetByCpfUseCase is an autogenerated mock type for the GetByCpfUseCase type
type MockGetByCpfUseCase struct {
	mock.Mock
}

type MockGetByCpfUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetByCpfUseCase) EXPECT() *MockGetByCpfUseCase_Expecter {
	return &MockGetByCpfUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockGetByCpfUseCase) Execute(command *commands.GetCustomerByCpfCommand) (*entities.Customer, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.GetCustomerByCpfCommand) (*entities.Customer, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.GetCustomerByCpfCommand) *entities.Customer); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(*commands.GetCustomerByCpfCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetByCpfUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetByCpfUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.GetCustomerByCpfCommand
func (_e *MockGetByCpfUseCase_Expecter) Execute(command interface{}) *MockGetByCpfUseCase_Execute_Call {
	return &MockGetByCpfUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockGetByCpfUseCase_Execute_Call) Run(run func(command *commands.GetCustomerByCpfCommand)) *MockGetByCpfUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.GetCustomerByCpfCommand))
	})
	return _c
}

func (_c *MockGetByCpfUseCase_Execute_Call) Return(_a0 *entities.Customer, _a1 error) *MockGetByCpfUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetByCpfUseCase_Execute_Call) RunAndReturn(run func(*commands.GetCustomerByCpfCommand) (*entities.Customer, error)) *MockGetByCpfUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetByCpfUseCase creates a new instance of MockGetByCpfUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetByCpfUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetByCpfUseCase {
	mock := &MockGetByCpfUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
